# Generated by Django 5.1 on 2026-05-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_summary_conversation_entrychunck_message_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='original_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='journal.entry'),
        ),
    ]
